"use client";

/**
 * ExplanationBlock — Phase 6 natural-language explanation panel.
 *
 * Calls /api/explain for the given (kind, id) in the selected language.
 * Shows a shimmer while loading, a source badge (AI vs Auto) after load,
 * and falls back to `initialFallback` text on any error — never goes blank.
 * Language preference persists for the browser session via sessionStorage.
 *
 * Sits ALONGSIDE authoritative numbers/evidence — never replaces them.
 */

import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import type { ExplainKind, ExplainLang, ExplainResponse } from "@/lib/types";
import { explain } from "@/lib/api";

// ── Session-persistent language preference ─────────────────────────────────────

const SESSION_KEY = "prohoripay-explain-lang";

export function getSessionLang(): ExplainLang {
  if (typeof window === "undefined") return "en";
  return (sessionStorage.getItem(SESSION_KEY) as ExplainLang) ?? "en";
}

export function setSessionLang(lang: ExplainLang) {
  if (typeof window !== "undefined") {
    sessionStorage.setItem(SESSION_KEY, lang);
  }
}

// ── Sub-components ─────────────────────────────────────────────────────────────

function SourceBadge({ source }: { source: "groq" | "fallback" }) {
  const isAi = source === "groq";
  return (
    <span
      className="inline-flex items-center px-1.5 py-0.5 rounded-sm text-label-sm shrink-0"
      style={{
        backgroundColor: isAi
          ? "color-mix(in srgb, var(--bv-brand) 12%, transparent)"
          : "color-mix(in srgb, var(--bv-text-secondary) 12%, transparent)",
        color: isAi ? "var(--bv-brand)" : "var(--bv-text-secondary)",
      }}
      title={
        isAi
          ? "Generated by Groq AI from the authoritative data"
          : "Auto-generated deterministic template"
      }
    >
      {isAi ? "AI" : "Auto"}
    </span>
  );
}

function Shimmer() {
  return (
    <div className="space-y-2" aria-label="Loading explanation" aria-busy="true">
      {[100, 83, 66].map((w) => (
        <div
          key={w}
          className="h-3 rounded-sm animate-pulse"
          style={{
            width: `${w}%`,
            backgroundColor: "var(--bv-surface-high)",
          }}
        />
      ))}
    </div>
  );
}

const LANG_LABELS: Record<ExplainLang, string> = {
  en: "EN",
  bn: "বাংলা",
  banglish: "Banglish",
};

// ── Main component ─────────────────────────────────────────────────────────────

interface ExplanationBlockProps {
  kind: ExplainKind;
  id: string;
  /**
   * Text to display immediately while the first API response is in-flight, and as
   * the fallback if every attempt fails. Never goes blank — the block is always
   * readable. For alerts this is typically the static Phase-3 template text.
   */
  initialFallback?: string;
}

export function ExplanationBlock({
  kind,
  id,
  initialFallback,
}: ExplanationBlockProps) {
  // Initialise lang from sessionStorage immediately — getSessionLang() returns
  // "en" on the server (where window is undefined) and the stored preference on
  // the client, so useState's lazy initialiser is safe to call here.
  const [lang, setLangState] = useState<ExplainLang>(() => getSessionLang());
  const [result, setResult] = useState<ExplainResponse | null>(null);
  const [loading, setLoading] = useState(false);
  // Track the latest request so a stale response is discarded.
  const reqRef = useRef(0);

  const fetchExplain = useCallback(
    async (k: ExplainKind, i: string, l: ExplainLang) => {
      const reqId = ++reqRef.current;
      setLoading(true);
      setResult(null);
      try {
        const res = await explain({ kind: k, id: i, lang: l });
        if (reqRef.current !== reqId) return; // stale
        setResult(res);
      } catch {
        if (reqRef.current !== reqId) return;
        // Graceful degradation — synthesise a fallback response.
        setResult({
          kind: k,
          id: i,
          lang: l,
          source: "fallback",
          text:
            initialFallback ??
            (l === "bn"
              ? "ব্যাখ্যা এই মুহূর্তে পাওয়া যায়নি। মানব পর্যালোচনা প্রয়োজন।"
              : l === "banglish"
                ? "Explanation ekhon pawa jacche na. Human review dorkar."
                : "Explanation unavailable. Human review recommended."),
        });
      } finally {
        if (reqRef.current === reqId) setLoading(false);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [id, kind, initialFallback],
  );

  // Fetch on mount and whenever lang, id, or kind changes.
  useEffect(() => {
    fetchExplain(kind, id, lang);
  }, [lang, id, kind, fetchExplain]);

  function handleLangChange(l: ExplainLang) {
    setLangState(l);
    setSessionLang(l);
  }

  const langs: ExplainLang[] = ["en", "bn", "banglish"];

  return (
    <div className="rounded-lg border border-default bg-surface-high p-3.5 space-y-3">
      {/* Header: label + language toggle */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <p className="text-label-sm text-secondary uppercase tracking-wide">
          Explanation
        </p>
        <div className="flex items-center gap-1">
          {langs.map((l) => (
            <button
              key={l}
              onClick={() => handleLangChange(l)}
              aria-pressed={lang === l}
              className={`px-2.5 py-1 rounded-pill text-label-sm transition-colors duration-fast focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand ${
                lang === l
                  ? "bg-brand text-on-brand"
                  : "bg-surface text-secondary border border-default hover:text-primary"
              }`}
            >
              {LANG_LABELS[l]}
            </button>
          ))}
        </div>
      </div>

      {/* Content area */}
      <AnimatePresence>
        {loading ? (
          <motion.div
            key="shimmer"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.12 }}
          >
            {/* Show initialFallback text faintly behind the shimmer so there's
                always something readable if loading takes long. */}
            {initialFallback ? (
              <p className="text-body-sm text-tertiary opacity-50 leading-relaxed">
                {initialFallback}
              </p>
            ) : (
              <Shimmer />
            )}
          </motion.div>
        ) : result ? (
          <motion.div
            key={`${result.lang}-${result.source}-${result.id}`}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.18 }}
            className="space-y-2"
          >
            <p className="text-body-sm text-primary leading-relaxed">
              {result.text}
            </p>
            <div className="flex items-center gap-1.5">
              <SourceBadge source={result.source} />
              <span className="text-body-sm text-tertiary">
                {result.source === "groq"
                  ? "AI-generated from live data"
                  : "Auto-generated template"}
              </span>
            </div>
          </motion.div>
        ) : initialFallback ? (
          // Pre-mount SSR placeholder — shows static text until client hydrates.
          <motion.p
            key="preflight"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="text-body-sm text-secondary leading-relaxed"
          >
            {initialFallback}
          </motion.p>
        ) : (
          <motion.div
            key="preflight-shimmer"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <Shimmer />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
